      outfile = out                    * recording the running information
      intxtfile = ../inputmapping/demo_pe.txt            * txt file generated by bismark
      outreadfile = anti_bisulfite          * the index of reads file in which the reads include methylated site
      flag = p                         * p means paired-ends; s means singled-end
      skipped_number = 1               * the number of the rows which will be skipped
      
     